apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgp-app-notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edgp-app-notification
  template:
    metadata:
      labels:
        app: edgp-app-notification
    spec:
      containers:
        - name: edgp-app-notification
          image: public.ecr.aws/q1b5w5y6/edgp-app-notification:VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: AWS_REGION
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: AUDIT_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: AUDIT_SQS_URL
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: FRONTEND_URL
            - name: CLIENT_INVITATION_USER_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: CLIENT_INVITATION_USER_URL
            - name: ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: ADMIN_URL
            - name: aws_access_key_id
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_edgp_access_key_id
            - name: aws_secret_key_id
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_edgp_secret_key_id
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_edgp_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_edgp_secret_key_id
          resources:
           requests:
             cpu: "50m"
             memory: "500Mi"
           limits:
             cpu: "350m"
             memory: "800Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: notification-k8s-service
spec:
  selector:
    app: edgp-app-notification
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: NodePort
